export const metadata = {
  title: "Application",
  description: "Generated by nextjs and Material UI",
};

export default function Home() {
  return (
    <>
      <h3>Hello World</h3>
    </>
  );
}
